sudo: true
language: node_js

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  directories:
  - $HOME/.yarn-cache

install:
  - yarn install

notifications:
  email: false

node_js:
  - stable
  - 7

script:
  - yarn test
  - yarn run compile

after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - yarn run coveralls
  - yarn run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
